import React, { useContext, useEffect, useState } from 'react';
import { UserDataContext } from '../Context/UserDataContext';
import { Link } from 'react-router-dom';
import CardSkelton from '../Components/Skelton/CardSkelton';
import axios from 'axios';
import Navbar from './Navbar';
import { toast } from 'react-toastify';
function PersonalisedRecommondation() {
  const [movies, setMovies] = useState([]);
  const [loading, setLoading] = useState(true);
  const { user } = useContext(UserDataContext);

  useEffect(() => {
    const fetchRecommended = async () => {
      try {
        const response = await axios.get(
          `${import.meta.env.VITE_BASE_URL}/recommondations/recommondation`,
          { withCredentials: true }
        );
        if (Array.isArray(response.data) && response.data[1].length === 0) {
            setMovies([]);
            setMessage(response.data[0]); 
          } else {
            setMovies(response.data); 
            setMessage('');
          }
      } catch (error) {
        console.error("Error fetching recommended movies:", error);
        toast.error(error.response.error)
      } finally {
        setLoading(false);
      }
    };

    fetchRecommended();
  }, []);

  return (
    <>
        <div>
        <Navbar/>
        </div>
    <section className="min-h-screen  py-10 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-10">
          <h1 className="text-3xl font-semibold text-white">
            Your Curated List of Movies
          </h1>
          <h3 className="text-xl font-medium text-gray-600 mt-2">
            Generated by our own AI model
          </h3>
        </div>

        {loading ? (
        <div className="flex flex-wrap justify-center gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <CardSkelton key={i} />
          ))}
        </div>
      ) : movies.length === 0 ? (
        <div className="flex justify-center">
          <div className="bg-[#141b23] text-white p-6 rounded-lg shadow-md text-center max-w-md w-full">
            <h3 className="text-xl font-semibold mb-2">No Recommendations Yet</h3>
            <p className="text-sm">Your recommended movies will appear here once our system has enough data based on your activity.</p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
          {movies.map((movie, idx) => (
            <div
              key={idx}
              className="bg-[#141b23] rounded-lg shadow-md text-white overflow-hidden"
            >
              <Link to={`/movie/${movie._id}`}>
                <img
                  className="h-64 w-full object-cover"
                  src={movie.poster}
                  alt={movie.title}
                />
              </Link>
              <div className="p-4 text-sm">
                <p><strong>Title:</strong> {movie.title}</p>
                <p><strong>Genre:</strong> {movie.genres.slice(0, 2).join(', ')}</p>
                <div className="mt-3 flex gap-2">
                  <Link to={`/movie/${movie._id}/review`} className="w-1/2">
                    <button className="w-full bg-green-500 hover:bg-green-700 py-2 rounded-md font-semibold">
                      Review
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          ))}
          </div>
        )}
      </div>
    </section>
    </>
  );
}

export default PersonalisedRecommondation;
